vim.cmd("highlight Normal guibg=NONE")
vim.cmd("highlight LineNr guifg=NvimLightCyan")
vim.cmd("highlight LineNrAbove guifg=NvimDarkCyan")
vim.cmd("highlight LineNrBelow guifg=NvimDarkCyan")
vim.cmd("highlight StatusLine guibg=NONE guifg=NvimLightGrey2")
vim.cmd("highlight StatusLineNC guibg=NONE guifg=NvimLightGrey2")
vim.cmd("highlight NormalFloat guibg=NONE")
